version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=leadflowx
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - leadflowx-network

  leadflowx-config-service:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/leadflowx
      - DB_URL=postgresql://postgres:postgres@postgres:5432/leadflowx
      - API_KEY=leadflowx-api-key-2025
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - leadflowx-network
    ports:
      - "8080:8080"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - leadflowx-network
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - leadflowx-network

networks:
  leadflowx-network:
    external: true
    name: leadflowx-network
