global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'leadflowx-config-service'
    static_configs:
      - targets: ['leadflowx-config-service:9090']
    metrics_path: /metrics

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'
